config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :posts
  resources :todos
  get 'home/about'
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_now

        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'ToDo App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Posts', posts_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'ToDos', todos_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'signup', new_user_path, class:"nav-link" %>
        </li>

      
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="p-5 m-4 bg-dark text-light rounded-3">
  <h1 class="display-4 text-light">About The App</h1>
  <p class="lead">This is a simple todo app for listing your ToDo's</p>
  <hr class="my-4">
  <p>You can add, update, view and delete your ToDo's.</p>
  <p class="lead">
    <%= link_to "Start", todos_path, class:"btn btn-primary btn-lg" %>
  </p>
</div>

app/views/home/index.html.erb
<div class="p-5 m-4 bg-dark text-light rounded-3">
  <h1 class="display-4 text-light">Hello, world!</h1>
  <p class="lead">This is a simple todo app for listing your ToDo's</p>
  <hr class="my-4">
  <p>You can add, update, view and delete your ToDo's.</p>
  <p class="lead">
    <%= link_to "Learn More", home_about_path, class:"btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>    
    
    <%= render 'home/header' %>

    <div class = "container-fluid">

      <%= yield %>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :body, class:"form-label mt-2" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary mt-4"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-4">

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<div class="d-flex justify-content-center">
<%= link_to 'Show', @post, class:"btn btn-outline-primary  me-2" %>
<%= link_to 'Back', posts_path, class:"btn btn-outline-secondary  ms-2" %>
</div>

</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<div class="d-flex">
  <h1>Posts</h1>
  <%= link_to 'Create New Post', new_post_path, class:"ms-auto btn btn-success btn-lg" %>
</div>

<% @posts.each do |post| %>
      <div class="card p-4 mt-4">
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text"><%= post.body %></p>
        <div class="d-flex mt-4">
        <%= link_to 'Show', post, class:"btn btn-outline-secondary m-2" %>
        <%= link_to 'Edit', edit_post_path(post), class:"btn btn-outline-secondary m-2" %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, 
        class:"btn btn-outline-secondary m-2" %>
        </div>
      </div>
    <% end %>

<br>


</div>

app/views/posts/new.html.erb
<div class="container mt-4">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"btn btn-outline-secondary mt-2" %>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<div class="d-flex justify-content-center h3">
<%= 'Post No.' + @post.id.to_s %>
</div>

<div class = "p-5 m-4 bg-secondary text-light rounded-3">

<p class="h3">
  <%= @post.title %>
</p>

<p class="h5 mt-4">
  <%= @post.body %>
</p>
</div>

<div class="d-flex justify-content-center mt-4">
<%= link_to 'Edit', edit_post_path(@post), class:"btn btn-outline-primary  me-2" %>
<%= link_to 'Back', posts_path, class:"btn btn-outline-primary  ms-2" %>
</div>

</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field mt-4">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success mt-4" %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="container mt-4">
    <h1>Editing Todo</h1>

    <%= render 'form', todo: @todo %>


    <div class="d-flex justify-content-center">
        <%= link_to 'Show', @todo, class:"btn btn-outline-primary  me-2" %>
        <%= link_to 'Back', todos_path, class:"btn btn-outline-secondary  ms-2" %>
    </div>
</div>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h4 class="d-flex justify-content-center mt-5">Todo List</h4>

<table class = "table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td class = "col-2"><%= todo.title %></td>
        <td class = "col-6"><%= todo.description %></td>
        <td class = "col-1"><%= link_to 'View', todo, class:"btn btn-outline-success col-12" %></td>
        <td class = "col-1"><%= link_to 'Edit', edit_todo_path(todo), class:"btn btn-outline-primary col-12" %></td>
        <td class = "col-1"><%= link_to 'Delete', todo, class:"btn btn-outline-danger col-12", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Todo', new_todo_path, class:"btn btn-lg btn-success" %>
</div>

app/views/todos/new.html.erb
<div class="container">
</div>

<div class="container">

<h3 class="mt-4">Add Todo</h3>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path, class:"btn btn-outline-secondary btn-sm mt-4 ps-4 pe-4" %>

</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center h3">
<%= 'ToDo No.' + @todo.id.to_s %>
</div>

<div class = "p-5 m-4 bg-dark text-light rounded-3">

<p class="d-flex justify-content-center h3">
  <%= @todo.title %>
</p>

<p class="d-flex justify-content-center h5 mt-4">
  <%= @todo.description %>
</p>

</div>

<br/>
<br/>

<div class="d-flex justify-content-center">
<%= link_to 'Back', todos_path, class:"btn btn-outline-secondary  me-2" %>
<%= link_to 'Edit', edit_todo_path(@todo), class:"btn btn-outline-primary ms-2" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>